prometheus-operator:
  prometheusOperator:
    createCustomResource: false
  ## Using default values from https://github.com/helm/charts/blob/master/stable/grafana/values.yaml
  ##
  grafana:
    #grafana.ini:
    #  server:
    #    root_url: "%(protocol)s://%(domain)s:%(http_port)s/"
    enabled: true

    ## Deploy default dashboards.
    ##
    defaultDashboardsEnabled: true

    adminPassword: admin

    ingress:
      ## If true, Grafana Ingress will be created
      ##
      enabled: true

      ## Annotations for Grafana Ingress
      ##
      annotations:
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/rewrite-target: /$1
        nginx.ingress.kubernetes.io/backend-protocol: "HTTP"

      ## Labels to be added to the Ingress
      ##
      labels: {}

      ## Hostnames.
      ## Must be provided if Ingress is enable.
      ##
      hosts:
        - "monitoring.twc-oap-cluster.us-south.containers.appdomain.cloud"

      ## Path for grafana ingress
      path: "/"

      ## TLS configuration for grafana Ingress
      ## Secret must be manually created in the namespace
      ##
      tls:
        - secretName: twc-oap-cluster
          hosts:
            - monitoring.twc-oap-cluster.us-south.containers.appdomain.cloud
